# Generated by Django 4.1.6 on 2023-02-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order_orderdetail_product_delete_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='This is a product', max_length=150),
        ),
    ]
